#!/bin/sh
Usage(){
	echo "usage:"
	echo ""
	echo "    screen-rotate <direction>"
	echo "    direction: up right down or left"
}
case $1 in 
	"up")
		xinput set-prop 'pointer:SYNA7500:00 06CB:3AF0' 'Coordinate Transformation Matrix' 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0
		xrandr -o normal;;
	"down")
		xinput set-prop 'pointer:SYNA7500:00 06CB:3AF0' 'Coordinate Transformation Matrix' -1.0, 0.0, 1.0, 0.0, -1.0, 1.0, 0.0, 0.0, 1.0
		xrandr -o inverted;;
	"right")
		xinput set-prop 'pointer:SYNA7500:00 06CB:3AF0' 'Coordinate Transformation Matrix' 0.0, 1.0, 0.0, -1.0, 0.0, 1.0, 0.0, 0.0, 1.0
		xrandr -o right;;
	"left")
		xinput set-prop 'pointer:SYNA7500:00 06CB:3AF0' 'Coordinate Transformation Matrix' 0.0, -1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0
		xrandr -o left;;
	*)
		Usage
esac

